# Generated by Django 4.2.3 on 2023-08-21 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0003_alter_examinations_cat_alter_examinations_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinations',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='examinations.category', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='examinations',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
