# Generated by Django 4.2.3 on 2023-09-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0005_examinations_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinations',
            name='user',
        ),
    ]
